apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: shared  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.0.136
    path: "/export/bc2_fs07/projects/scicore_kube"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared  
  resources:
    requests:
      storage: 8Gi
